"""Readable byte-level BPE, without regex pre-tokenization or third-party libraries.

This is a teaching implementation: repeated whole-corpus scans favor clarity
over production speed. Each document is merged independently.
"""

import json
from pathlib import Path


def count_pairs(token_ids: list[int]) -> dict[tuple[int, int], int]:
    """Count adjacent pairs, including overlapping occurrences."""
    counts = {}
    for i in range(len(token_ids) - 1):
        pair = (token_ids[i], token_ids[i + 1])
        counts[pair] = counts.get(pair, 0) + 1
    return counts


def merge_pair(token_ids: list[int], pair: tuple[int, int], new_id: int) -> list[int]:
    """Replace non-overlapping matches from left to right."""
    result = []
    i = 0
    while i < len(token_ids):
        if i + 1 < len(token_ids) and (token_ids[i], token_ids[i + 1]) == pair:
            result.append(new_id)
            i += 2
        else:
            result.append(token_ids[i])
            i += 1
    return result


class ByteBPETokenizer:
    BOS_ID = 256
    EOS_ID = 257
    PAD_ID = 258
    SPECIAL_TOKENS = {256: "<BOS>", 257: "<EOS>", 258: "<PAD>"}
    FIRST_MERGE_ID = 259

    def __init__(self, vocab_size: int = 512):
        if type(vocab_size) is not int or vocab_size < self.FIRST_MERGE_ID:
            raise ValueError("vocab_size must be an integer >= 259")
        self.target_vocab_size = vocab_size
        self._reset()

    def _reset(self) -> None:
        # Special Tokens are separate: they do not represent literal byte strings.
        self.vocab = {i: bytes([i]) for i in range(256)}
        self.merges: dict[tuple[int, int], int] = {}

    @property
    def vocab_size(self) -> int:
        """Actual size can be smaller than the requested maximum."""
        return len(self.vocab) + len(self.SPECIAL_TOKENS)

    def train(self, text: str | list[str]) -> None:
        """Learn rules from TRAINING text only; never merge across documents."""
        documents = [text] if isinstance(text, str) else text
        if not isinstance(documents, list) or not all(isinstance(d, str) for d in documents):
            raise TypeError("Expected a string or list of strings")
        sequences = [list(document.encode("utf-8")) for document in documents]
        self._reset()
        while self.vocab_size < self.target_vocab_size:
            counts = {}
            for sequence in sequences:
                for pair, count in count_pairs(sequence).items():
                    counts[pair] = counts.get(pair, 0) + count
            if not counts:
                break
            # Frequency first; lexicographic Pair order breaks ties deterministically.
            pair = min(counts, key=lambda p: (-counts[p], p))
            new_id = self.vocab_size
            self.merges[pair] = new_id
            self.vocab[new_id] = self.vocab[pair[0]] + self.vocab[pair[1]]
            sequences = [merge_pair(sequence, pair, new_id) for sequence in sequences]

    def encode(self, text: str, *, add_bos: bool = False, add_eos: bool = False) -> list[int]:
        """Apply existing rules in Rank order; do not learn new rules."""
        token_ids = list(text.encode("utf-8"))
        while len(token_ids) >= 2:
            candidates = [pair for pair in count_pairs(token_ids) if pair in self.merges]
            if not candidates:
                break
            # Merge IDs increase with training order, so smaller ID = earlier Rank.
            pair = min(candidates, key=self.merges.__getitem__)
            token_ids = merge_pair(token_ids, pair, self.merges[pair])
        if add_bos:
            token_ids.insert(0, self.BOS_ID)
        if add_eos:
            token_ids.append(self.EOS_ID)
        return token_ids

    def decode(self, token_ids: list[int], *, skip_special_tokens: bool = False,
               errors: str = "strict") -> str:
        """Join bytes BEFORE UTF-8 decoding; generated bytes may be invalid UTF-8.

        Use errors='replace' for displaying arbitrary generated sequences.
        Literal '<BOS>' in input text is ordinary text, not an injected Special ID.
        """
        pieces = []
        for token_id in token_ids:
            if token_id in self.SPECIAL_TOKENS:
                if not skip_special_tokens:
                    pieces.append(self.SPECIAL_TOKENS[token_id].encode("utf-8"))
            elif token_id in self.vocab:
                pieces.append(self.vocab[token_id])
            else:
                raise ValueError(f"Unknown Token ID: {token_id}")
        return b"".join(pieces).decode("utf-8", errors=errors)

    def save(self, path: str | Path) -> None:
        """Store ordered rules; expanded vocabulary is reconstructed on load."""
        payload = {
            "format": "deerlight-byte-bpe-v1",
            "target_vocab_size": self.target_vocab_size,
            "special_tokens": {str(k): v for k, v in self.SPECIAL_TOKENS.items()},
            "merges": [[a, b, new_id] for (a, b), new_id in self.merges.items()],
        }
        Path(path).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> "ByteBPETokenizer":
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        if payload.get("format") != "deerlight-byte-bpe-v1":
            raise ValueError("Unsupported Tokenizer format")
        if payload.get("special_tokens") != {str(k): v for k, v in cls.SPECIAL_TOKENS.items()}:
            raise ValueError("Incompatible Special Tokens")
        tokenizer = cls(payload["target_vocab_size"])
        for a, b, new_id in payload["merges"]:
            if (any(type(i) is not int for i in (a, b, new_id))
                    or a not in tokenizer.vocab or b not in tokenizer.vocab
                    or new_id != tokenizer.vocab_size
                    or (a, b) in tokenizer.merges
                    or new_id >= tokenizer.target_vocab_size):
                raise ValueError("Invalid Merge Rule")
            tokenizer.merges[(a, b)] = new_id
            tokenizer.vocab[new_id] = tokenizer.vocab[a] + tokenizer.vocab[b]
        return tokenizer


if __name__ == "__main__":
    tokenizer = ByteBPETokenizer(vocab_size=265)
    tokenizer.train("banana banana banana")
    print("Merge Rules:", tokenizer.merges)
    for text in ["banana", "Deerlight GPT", "鹿光 🦌", "<BOS>"]:
        ids = tokenizer.encode(text)
        # ASCII escapes keep this demo printable even in legacy Windows terminals.
        print(f"Text: {ascii(text)} | IDs: {ids} | Decoded: {ascii(tokenizer.decode(ids))}")
